export const NAV_LINKS = [
  { href: "/home/categories", label: "Categories", key: "categories" },
  { href: "/", label: "New Arrivals", key: "new arrivals" },
  { href: "/", label: "Features", key: "features" },
  { href: "/", label: "Collection", key: "collection" },
];

export const NEW_ARRIVALS = [
  {
    img: "/images/new_arrival/denim_jackets.jpg",
    alt: "image",
    title: "Denim Men's Jacket",
    category: "denim-men-jacket",
    caption: "100% Cotton",
  },
  {
    img: "/images/new_arrival/winter_clothes.jpg",
    alt: "image",
    title: "Winter Clothes",
    category: "winter-clothes",
    caption: "100% Cotton",
  },
  {
    img: "/images/new_arrival/men_winter_jacket.jpg",
    alt: "image",
    title: "Men Winter Jacket",
    category: "men-winter-jacket",
    caption: "100% Cotton",
  },
  {
    img: "/images/new_arrival/black_clothes.jpg",
    alt: "image",
    title: "Black Clothes",
    category: "black-clothes",
    caption: "100% Cotton",
  },
];

export const CATEGORIES = [
  { src: "/icons/categories/img_sweater.svg", alt: "jacket", label: "Jacket" },
  { src: "/icons/categories/img_tshirt.svg", alt: "shirt", label: "T-Shirt" },
  { src: "/icons/categories/img_pants.svg", alt: "pants", label: "Pant" },
  { src: "/icons/categories/img_boot.svg", alt: "shoes", label: "Shoes" },
  { src: "/icons/categories/img_dress.svg", alt: "dress", label: "Dress" },
  {
    src: "/icons/categories/img_belt.svg",
    alt: "accessories",
    label: "Accesories",
  },
];

export const clothingCategoriesMen = [
  // For Men
  {
    label: "T-Shirts",
    slug: "t-shirts",
    gender: "men",
    imgUrl: "/icons/categories/men/tshirt.png",
  },
  {
    label: "Shirts",
    slug: "shirts",
    gender: "men",
    imgUrl: "/icons/categories/men/cloth.png",
  },
  {
    label: "Polo Shirts",
    slug: "polo-shirts",
    gender: "men",
    imgUrl: "/icons/categories/men/polo-shirt.png",
  },
  {
    label: "Hoodies & Sweatshirts",
    slug: "hoodies-sweatshirts",
    gender: "men",
    imgUrl: "/icons/categories/men/hoodie.png",
  },
  {
    label: "Jackets & Coats",
    slug: "jackets-coats",
    gender: "men",
    imgUrl: "/icons/categories/men/jacket.png",
  },
  {
    label: "Jeans",
    slug: "jeans",
    gender: "men",
    imgUrl: "/icons/categories/men/jeans.png",
  },
  {
    label: "Pants & Trousers",
    slug: "pants-trousers",
    gender: "men",
    imgUrl: "/icons/categories/men/trouser.png",
  },
  {
    label: "Shorts",
    slug: "shorts",
    gender: "men",
    imgUrl: "/icons/categories/men/denim-shorts.png",
  },
  {
    label: "Suits & Blazers",
    slug: "suits-blazers",
    gender: "men",
    imgUrl: "/icons/categories/men/blazer.png",
  },
  {
    label: "Activewear",
    slug: "activewear",
    gender: "men",
    imgUrl: "/icons/categories/men/sportswear.png",
  },
  {
    label: "Swimwear",
    slug: "swimwear",
    gender: "men",
    imgUrl: "/icons/categories/men/swimwear.png",
  },
  {
    label: "Underwear & Socks",
    slug: "underwear-socks",
    gender: "men",
    imgUrl: "/icons/categories/men/boxers.png",
  },
  {
    label: "Sleepwear & Loungewear",
    slug: "sleepwear-loungewear",
    gender: "men",
    imgUrl: "/icons/categories/men/night.png",
  },
  {
    label: "Formal Wear",
    slug: "formal-wear",
    gender: "men",
    imgUrl: "/icons/categories/men/suit.png",
  },
  {
    label: "Traditional Wear",
    slug: "traditional-wear",
    gender: "men",
    imgUrl: "/icons/categories/men/kurta.png",
  },
  {
    label: "Shoes",
    slug: "shoes",
    gender: "men",
    imgUrl: "/icons/categories/men/shoes.png",
  },
];

export const clothingCategoriesWomen = [
  // For Women
  {
    label: "T-Shirts & Tops",
    slug: "t-shirts-tops",
    gender: "women",
    imgUrl: "/icons/categories/women/",
  },
  {
    label: "Blouses & Shirts",
    slug: "blouses-shirts",
    gender: "women",
    imgUrl: "/icons/categories/women/",
  },
  {
    label: "Dresses",
    slug: "dresses",
    gender: "women",
    imgUrl: "/icons/categories/women/",
  },
  {
    label: "Skirts",
    slug: "skirts",
    gender: "women",
    imgUrl: "/icons/categories/women/",
  },
  {
    label: "Jeans",
    slug: "jeans",
    gender: "women",
    imgUrl: "/icons/categories/women/",
  },
  {
    label: "Pants & Trousers",
    slug: "pants-trousers",
    gender: "women",
    imgUrl: "/icons/categories/women/",
  },
  {
    label: "Shorts",
    slug: "shorts",
    gender: "women",
    imgUrl: "/icons/categories/women/",
  },
  {
    label: "Jumpsuits & Rompers",
    slug: "jumpsuits-rompers",
    gender: "women",
    imgUrl: "/icons/categories/women/",
  },
  {
    label: "Outerwear",
    slug: "outerwear",
    gender: "women",
    imgUrl: "/icons/categories/women/",
  },
  {
    label: "Sweaters & Cardigans",
    slug: "sweaters-cardigans",
    gender: "women",
    imgUrl: "/icons/categories/women/",
  },
  {
    label: "Activewear & Gymwear",
    slug: "activewear-gymwear",
    gender: "women",
    imgUrl: "/icons/categories/women/",
  },
  {
    label: "Swimwear & Beachwear",
    slug: "swimwear-beachwear",
    gender: "women",
    imgUrl: "/icons/categories/women/",
  },
  {
    label: "Lingerie & Intimates",
    slug: "lingerie-intimates",
    gender: "women",
    imgUrl: "/icons/categories/women/",
  },
  {
    label: "Sleepwear & Loungewear",
    slug: "sleepwear-loungewear",
    gender: "women",
    imgUrl: "/icons/categories/women/",
  },
  {
    label: "Formal Wear",
    slug: "formal-wear",
    gender: "women",
    imgUrl: "/icons/categories/women/",
  },
  {
    label: "Traditional Wear",
    slug: "traditional-wear",
    gender: "women",
    imgUrl: "/icons/categories/women/",
  },
  {
    label: "Accessories",
    slug: "accessories",
    gender: "women",
    imgUrl: "/icons/categories/women/",
  },
  {
    label: "Shoes",
    slug: "shoes",
    gender: "women",
    imgUrl: "/icons/categories/women/",
  },
  {
    label: "Bags",
    slug: "bags",
    gender: "women",
    imgUrl: "/icons/categories/women/",
  },
];

export const FEATURED = [
  {
    src: "/images/featured/img_placeholder_1.png",
    alt: "1",
    label: "White Sweatshirt",
    price: "20",
  },
  {
    src: "/images/featured/img_placeholder_2.png",
    alt: "2",
    label: "Green Hoodie",
    price: "30",
  },
  {
    src: "/images/featured/img_placeholder_3.png",
    alt: "3",
    label: "Purpule Hoodie",
    price: "25",
  },
  {
    src: "/images/featured/img_placeholder_4.png",
    alt: "4",
    label: "Light Green",
    price: "15",
  },
  {
    src: "/images/featured/img_placeholder_5.png",
    alt: "5",
    label: "Pink Purse",
    price: "10",
  },
  {
    src: "/images/featured/img_placeholder_17.png",
    alt: "6",
    label: "Pink Hoodie",
    price: "20",
  },
];

export const WHY_CHOOSE_US = [
  {
    src: "/icons/service/img_truck.svg",
    alt: "truck",
    label: "Free Shipping",
    description: "This free shipping only for selected region",
  },
  {
    src: "/icons/service/img_card.svg",
    alt: "card",
    label: "Secure Payment",
    description: "This secure payment only for selected region",
  },
  {
    src: "/icons/service/img_broken.svg",
    alt: "return",
    label: "Warrenty",
    description: "This return policy only for selected region",
  },
  {
    src: "/icons/service/img_support.svg",
    alt: "support",
    label: "24/7 Support",
    description: "This 24/7 support only for selected region",
  },
];

export const PRODUCT = [
  {
    id: 1,
    imgUrls: [
      "/images/features/img_placeholder_1.png",
      "/images/features/img_placeholder_2.png",
      "/images/features/img_placeholder_3.png",
      "/images/features/img_placeholder_4.png",
    ],
    alt: "white sweatshirt",
    label: "White Sweatshirt",
    category: "jacket",
    gender: "MEN",
    brand: "Nike",
    price: 20,
    discount: 20,
    prevPrice: 25,
    offers: [
      {
        id: 1,
        discount: 5,
        code: "GET5",
        description: "Get 5% off on this product using HDFC Credit Card",
      },
    ],
    ratings: [
      { id: 1, rating: 1, userId: 1 },
      { id: 2, rating: 2, userId: 2 },
      { id: 3, rating: 2, userId: 3 },
      { id: 4, rating: 3, userId: 4 },
      { id: 5, rating: 4, userId: 6 },
      { id: 6, rating: 4, userId: 7 },
      { id: 7, rating: 5, userId: 8 },
      { id: 8, rating: 4, userId: 5 },
    ],
    averageRating: 3.5,
    totalRatings: 8,
    reviews: [
      {
        id: 1,
        name: "John Doe",
        rating: 4,
        review: "This is a great product",
        imgUrls: [
          "/images/features/img_placeholder_1.png",
          "/images/features/img_placeholder_2.png",
          "/images/features/img_placeholder_3.png",
        ],
      },
    ],
    colors: ["WHITE", "BLACK", "RED", "BLUE"],
    sizes: ["S", "M", "L", "XL"],
    isBestSeller: true,
  },
];

export const PRODUCTS = [
  {
    id: 1,
    imgUrls: [
      "https://lp2.hm.com/hmgoepprod?set=quality%5B79%5D%2Csource%5B%2Fca%2Ff1%2Fcaf103a6aa46f344c40d2cde0bb25029c3130ecc.jpg%5D%2Corigin%5Bdam%5D%2Ccategory%5B%5D%2Ctype%5BLOOKBOOK%5D%2Cres%5Bm%5D%2Chmver%5B1%5D&call=url[file:/product/main]",
      "/images/featured/img_placeholder_2.png",
      "/images/featured/img_placeholder_3.png",
      "/images/featured/img_placeholder_4.png",
    ],
    alt: "white sweatshirt",
    label: "White Sweatshirt",
    category: "jacket",
    gender: "MEN",
    brand: "Nike",
    price: 20,
    offer: 20,
    colors: ["white", "black", "red", "blue"],
    prevPrice: 25,
    averageRating: 3.5,
    totalRatings: 8,
    isBestSeller: true,
  },
  {
    id: 2,
    imgUrls: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQwB9WqtDmwdVHv06yNTMEpmvv4VDL5WabNBQ&s",
      "/images/features/img_placeholder_17.png",
      "/images/features/img_placeholder_17.png",
      "/images/features/img_placeholder_17.png",
    ],
    alt: "green hoodie",
    label: "Green Hoodie",
    category: "jacket",
    gender: "MEN",
    brand: "Nike",
    price: 20,
    offer: 20,
    prevPrice: 25,
    averageRating: 3.5,
    colors: ["white", "black", "red"],

    totalRatings: 8,
    isBestSeller: false,
  },
  {
    id: 3,
    imgUrls: [
      "https://assets.myntassets.com/f_webp,dpr_1.5,q_60,w_210,c_limit,fl_progressive/assets/images/27226100/2024/1/29/0d63dbfd-673d-49d0-be10-751fa0d54c0f1706543722864BULLMERMenTribalPrintedAppliqueT-shirt1.jpg",
      "/images/features/img_placeholder_2.png",
      "/images/features/img_placeholder_3.png",
      "/images/features/img_placeholder_2.png",
    ],
    alt: "purple hoodie",
    label: "Purple Hoodie",
    category: "jacket",
    gender: "WOMEN",
    brand: "Zudio",
    price: 24,
    offer: 20,
    prevPrice: 30,
    averageRating: 3.5,
    colors: ["white", "blue"],

    totalRatings: 8,
    isBestSeller: true,
  },
  {
    id: 4,
    imgUrls: [
      "/images/featured/img_placeholder_3.png",
      "/images/features/img_placeholder_4.png",
      "/images/features/img_placeholder_5.png",
      "/images/features/img_placeholder_17.png",
    ],
    alt: "light green",
    label: "Light Green",
    category: "jacket",
    gender: "WOMEN",
    brand: "Adidas",
    price: 20,
    offer: 20,
    prevPrice: 25,
    averageRating: 3.5,
    colors: ["white", "black", "violet", "blue"],

    totalRatings: 8,
    isBestSeller: false,
  },
  {
    id: 5,
    imgUrls: [
      "/images/featured/img_placeholder_3.png",
      "/images/features/img_placeholder_4.png",
      "/images/features/img_placeholder_5.png",
      "/images/features/img_placeholder_17.png",
    ],
    alt: "light green",
    label: "Light Green",
    category: "jacket",
    gender: "WOMEN",
    brand: "Adidas",
    price: 20,
    offer: 20,
    prevPrice: 25,
    isBestSeller: false,
    colors: ["white", "black", "red", "blue"],
  },
  {
    id: 6,
    imgUrls: [
      "/images/featured/img_placeholder_3.png",
      "/images/features/img_placeholder_4.png",
      "/images/features/img_placeholder_5.png",
      "/images/features/img_placeholder_17.png",
    ],
    alt: "light green",
    label: "Light Green",
    category: "jacket",
    gender: "WOMEN",
    brand: "Adidas",
    price: 20,
    offer: 20,
    prevPrice: 25,
    isBestSeller: false,
  },
  {
    id: 7,
    imgUrls: [
      "/images/featured/img_placeholder_3.png",
      "/images/features/img_placeholder_4.png",
      "/images/features/img_placeholder_5.png",
      "/images/features/img_placeholder_17.png",
    ],
    alt: "light green",
    label: "Light Green",
    category: "jacket",
    gender: "WOMEN",
    brand: "Adidas",
    price: 20,
    offer: 20,
    prevPrice: 25,
    isBestSeller: false,
  },
  {
    id: 8,
    imgUrls: [
      "/images/featured/img_placeholder_3.png",
      "/images/features/img_placeholder_4.png",
      "/images/features/img_placeholder_5.png",
      "/images/features/img_placeholder_17.png",
    ],
    alt: "light green",
    label: "Light Green",
    category: "jacket",
    gender: "WOMEN",
    brand: "Adidas",
    price: 20,
    offer: 20,
    prevPrice: 25,
    isBestSeller: false,
  },
  {
    id: 9,
    imgUrls: [
      "/images/featured/img_placeholder_3.png",
      "/images/features/img_placeholder_4.png",
      "/images/features/img_placeholder_5.png",
      "/images/features/img_placeholder_17.png",
    ],
    alt: "light green",
    label: "Light Green",
    category: "jacket",
    gender: "WOMEN",
    brand: "Adidas",
    price: 20,
    offer: 20,
    prevPrice: 25,
    isBestSeller: false,
  },
  {
    id: 10,
    imgUrls: [
      "/images/featured/img_placeholder_3.png",
      "/images/features/img_placeholder_4.png",
      "/images/features/img_placeholder_5.png",
      "/images/features/img_placeholder_17.png",
    ],
    alt: "light green",
    label: "Light Green",
    category: "jacket",
    gender: "WOMEN",
    brand: "Adidas",
    price: 20,
    offer: 20,
    prevPrice: 25,
    isBestSeller: false,
  },
  {
    id: 11,
    imgUrls: [
      "/images/featured/img_placeholder_3.png",
      "/images/features/img_placeholder_4.png",
      "/images/features/img_placeholder_5.png",
      "/images/features/img_placeholder_17.png",
    ],
    alt: "light green",
    label: "Light Green",
    category: "jacket",
    gender: "WOMEN",
    brand: "Adidas",
    price: 20,
    offer: 20,
    prevPrice: 25,
    isBestSeller: false,
  },
];

export const FILTER = {
  brands: [
    { label: "Nike", value: "nike", id: 1 },
    { label: "Adidas", value: "adidas", id: 2 },
    { label: "Zara", value: "zara", id: 3 },
    { label: "H & M", value: "h&m", id: 4 },
    { label: "Zudio", value: "zudio", id: 5 },
  ],
  price: [
    { label: "Under $25", value: "0-25" },
    { label: "$25 to $50", value: "25-50" },
    { label: "$50 to $100", value: "50-100" },
    { label: "Over $100", value: "100-" },
  ],
  colors: [
    { label: "Red", value: "red" },
    { label: "Blue", value: "blue" },
    { label: "Green", value: "green" },
    { label: "Yellow", value: "yellow" },
  ],
  sizes: [
    { label: "S", value: "s" },
    { label: "M", value: "m" },
    { label: "L", value: "l" },
    { label: "XL", value: "xl" },
  ],
};

const USER = {
  id: 1,
  name: "John Doe",
  email: "johndoe@gmail.com",
  password: "password",
  img: "/images/users/img_placeholder_1.png",
  address: {
    street: "123 Main St",
    city: "New York",
    state: "NY",
    zip: "12345",
    country: "USA",
  },
  phone: "+91 1234567890",
  orders: [
    {
      id: 1,
      totalPrice: 40,
      products: [
        {
          id: 1,
          label: "White Sweatshirt",
          category: "jacket",
          brand: "Nike",
          price: 20,
        },
        {
          id: 2,
          label: "Green Hoodie",
          category: "jacket",
          brand: "Nike",
          price: 20,
        },
      ],
    },
  ],
  cart: [
    {
      id: 1,
      label: "White Sweatshirt",
      category: "jacket",
      brand: "Nike",
      price: 20,
    },
    {
      id: 2,
      label: "Green Hoodie",
      category: "jacket",
      brand: "Nike",
      price: 20,
    },
  ],
  transactions: [
    {
      id: 1,
      orderId: 1,
      date: "2021-09-30T00:00:00.000Z",
      amount: 40,
      status: "success",
    },
  ],
  reviews: [
    {
      id: 1,
      productId: 1,
      rating: 4,
      review: "This is a great product",
    },
    {
      id: 2,
      productId: 2,
      rating: 3,
      review: "This is a good product",
    },
  ],
};
